package com.example.coinquest.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single financial transaction (Income or Expense) in the database.
 * 
 * @property id Unique identifier for the transaction, automatically generated by Room.
 * @property title A brief description or name for the transaction (e.g., "Grocery", "Salary").
 * @property amount The monetary value of the transaction.
 * @property category The classification group for the transaction (e.g., "Food", "Transport").
 * @property date The timestamp (in milliseconds) when the transaction occurred or was recorded.
 * @property isIncome Boolean flag: true if the transaction is an income, false if it is an expense.
 * @property imageUri Optional string path to an image associated with the transaction (e.g., a receipt).
 */
@Entity(tableName = "transactions")
data class Transaction(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val title: String,
    val amount: Double,
    val category: String,
    val date: Long,
    val isIncome: Boolean,
    val imageUri: String? = null
)
